In [1]:
import os 
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn import preprocessing

import warnings
warnings.filterwarnings("ignore")
os.chdir("C:/Users/Abhishek/Desktop/UpGrade/Day 22-23 Decision tree and RF/Titanic")

data=pd.read_csv("Train.csv")
data.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [2]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [3]:
data_final=pd.DataFrame(data=data,columns=['PassengerId', 'Survived', 'Pclass','Sex', 'Age', 'SibSp','Parch','Fare', 'Embarked'])
encoder = preprocessing.LabelEncoder()
data_final["Sex"]=encoder.fit_transform(data_final["Sex"])
data_final.head(2)

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    1  22.0      1      0   7.2500        S
1            2         1       1    0  38.0      1      0  71.2833        C

In [4]:
data_final["Age"]= data_final["Age"].fillna(data_final["Age"].mean())
data_final["Embarked"] = data_final["Embarked"].fillna(method="pad")
data_final.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [5]:
data_final=data_final.drop(["PassengerId","Embarked"],axis=1)

# Model

In [6]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import  accuracy_score,confusion_matrix
from sklearn.naive_bayes import *

In [7]:
loop_var = ["Survived","Pclass" , "Sex", "SibSp" , "Parch"]
loop_var

['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch']

In [8]:
for i in loop_var:
    y=data_final[i]
    x=data_final.drop([i],axis=1)
    print("\n \n For category :",i," As Dependent Variable -")
    #print(y.head(1))
    #print(x.head(1))
    #print("****************************")
    X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
    clf= BernoulliNB()
    y_pred = clf.fit(X_train,y_train).predict(X_test)
    print("Accuracy for Category :",i,"is :",accuracy_score(y_test,y_pred))
    print("Confusion Matrix for Category :",i,"is : \n",confusion_matrix(y_test,y_pred))


 
 For category : Survived  As Dependent Variable -
Accuracy for Category : Survived is : 0.7877094972067039
Confusion Matrix for Category : Survived is : 
 [[92 18]
 [20 49]]

 
 For category : Pclass  As Dependent Variable -
Accuracy for Category : Pclass is : 0.5865921787709497
Confusion Matrix for Category : Pclass is : 
 [[23  0 23]
 [17  0 21]
 [13  0 82]]

 
 For category : Sex  As Dependent Variable -
Accuracy for Category : Sex is : 0.7877094972067039
Confusion Matrix for Category : Sex is : 
 [[49 18]
 [20 92]]

 
 For category : SibSp  As Dependent Variable -
Accuracy for Category : SibSp is : 0.664804469273743
Confusion Matrix for Category : SibSp is : 
 [[108  14   0   0   0   0]
 [ 31  11   0   0   0   0]
 [  2   2   0   0   0   0]
 [  4   2   0   0   0   0]
 [  3   1   0   0   0   0]
 [  1   0   0   0   0   0]]

 
 For category : Parch  As Dependent Variable -
Accuracy for Category : Parch is : 0.7262569832402235
Confusion Matrix for Category : Parch is : 
 [[124  14   

# Only SEx and Survivor are categorical variables so Confusion matrix can be seen correctly for them.